name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: uv sync --frozen
    
    - name: Run tests
      env:
        TOKENIZERS_PARALLELISM: false
      run: |
        uv run python test_git_blame_tool.py
    
    - name: Test CLI commands directly
      env:
        TOKENIZERS_PARALLELISM: false
      run: |
        # Test help command
        uv run git_blame_search --help
        
        # Test indexing on current repo
        uv run git_blame_search index --max-commits 5
        
        # Test search
        uv run git_blame_search search "test" --limit 3
        
        # Test who command
        uv run git_blame_search who "code" --limit 3
    
    - name: Test MCP server startup
      env:
        TOKENIZERS_PARALLELISM: false
      run: |
        # Test that server can be imported
        uv run python -c "from src.server import mcp; print('MCP server imported successfully')"